HLT_triggers:

  "2016_PreVFP":
    DoubleEle: 
      - Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_DZ
    DoubleMuon: 
      - Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ
    MuonEG: 
      - Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL,
      - Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_DZ,
      - Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL,
      - Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZ
    SingleEle: 
      - Ele27 WPTight Gsf
    SingleMuon: 
      - IsoMu24


  "2016_PostVFP":
    DoubleEle: 
      - Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_DZ
    DoubleMuon: 
      - Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ
    MuonEG: 
      - Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL,
      - Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_DZ,
      - Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL,
      - Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZ
    SingleEle: 
      - Ele27 WPTight Gsf
    SingleMuon: 
      - IsoMu24


  "2017":
    DoubleEle: 
      - Ele23_Ele12_CaloIdL_TrackIdL_IsoVL,
      - Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_DZ
    DoubleMuon: 
      - Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ,
      - Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_Mass3p8
    MuonEG: 
      - Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL,
      - Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_DZ,
      - Mu12_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZ,
      - Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZ
    SingleEle: 
      - Ele32_WPTight_Gsf
    SingleMuon: 
      - IsoMu24_eta2p1,
      - IsoMu27
    

  "2018":
    DoubleEle: 
      - Ele23_Ele12_CaloIdL_TrackIdL_IsoVL,
      - Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_DZ
    DoubleMuon: 
      - Mu17 TrkIsoVVL Mu8 TrkIsoVVL DZ Mass3p8
    MuonEG: 
      - Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL,
      - Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_DZ,
      - Mu12_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZ,
      - Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZ
    SingleEle: 
      - Ele32_WPTight_Gsf
    SingleMuon: 
      - IsoMu24


  "2022_postEE":
    DoubleEle: 
      - Ele23_Ele12_CaloIdL_TrackIdL_IsoVL
    DoubleMuon: 
      - Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_Mass3p8
    MuonEG: 
      - Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_DZ
      - Mu12_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZ
    SingleEle: 
      - Ele30_WPTight_Gsf
    SingleMuon: 
      - IsoMu24


  "2023_preBPix":
    DoubleEle: 
      - Ele23_Ele12_CaloIdL_TrackIdL_IsoVL
    DoubleMuon: 
      - Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_Mass3p8
    MuonEG: 
      - Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_DZ
      - Mu12_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZ
    SingleEle: 
      - Ele30_WPTight_Gsf
    SingleMuon: 
      - IsoMu24


  "2023_postBPix":
    DoubleEle: 
      - Ele23_Ele12_CaloIdL_TrackIdL_IsoVL
    DoubleMuon: 
      - Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_Mass3p8
    MuonEG: 
      - Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_DZ
      - Mu12_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZ
    SingleEle: 
      - Ele30_WPTight_Gsf
    SingleMuon: 
      - IsoMu24
