plotting_style:
    
    opts_mc:
        histtype: "step"
        stack: false
#        linestyle: "dotted"
        
    colors_mc:
        ttHTobb_ttTo2L2Nu:
            [0., 0., 1., .9]
        ttZToQQ:
            [0., 0., 0., 0.75]
        ttbb_4f_TTTo2L2Nu:
            [1., 0., 0., .9]
    #randomize_colors: true
            
         
    #rescale_samples:
        #ttHTobb_ttTo2L2Nu: 3
        #ttZToQQ: 1200
        #ttbb_4f_TTTo2L2Nu: 350
        
        

